import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from "next/head";
import Footer from "../components/Footer";
import {Box} from '@material-ui/core';
import React from "react";
import '../styles/globals.scss';

export default function MyApp({ Component, pageProps }: AppProps) {
  return(
      <Box>
        <Head>
          <title>Main </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Component {...pageProps} />

        <Footer/>
      </Box>
  )
}
